config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do 
  get 'product/latest'

end

    root 'store#index' , as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy



 # Rails : we created a skeleton cart model .. i guess



   # now we need a smart add_product() method in our cart . One  checks whether our list
   # of items already include the product we are adding ; if it does , it bumps the quantity 
   #  , and if it doesn not , it builds the a new lineitem.
  def check_if_product_exist_increament_or_add_new_line_item(product_id)
       # product_id is the reference key for the product inside line_item tble 
       current_item = line_items.find_by(product_id: product_id)
    if current_item
      #Remember, this isn't Java. nil is an object of class NilClass.
      #nil does have methods you can call on it, but > 
      #isn't one of them. That's why you get NoMethodError
    
      #current_item.quantity = current_item.quantity + 1
       current_item.quantity += 1
   else
      current_item = line_items.build(product_id: product_id)
     #current_item.price = current_item.product.price
   end
    current_item
   end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
#---
#---
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  # throw an error here , if the cart is not found
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
     # The battle of routes: store_url vs store_path
      format.html { redirect_to store_url , notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  # ...
  private
  # ...

    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2> Your Cart </h2>


  
<%= render :partial => "line_items/line_item", :collection => cart.line_items %>

<div class="table_responsive">
<table class="table">

<tr class="info">
    <td> Total </td>
    <td> <%= number_to_currency(cart.total_price) %> </td>
</tr>

</table>
</div>
<%= button_to 'Empty cart me' , cart , method: :delete , 
    date: { confirm: 'Are you sure?' } %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<div class="table-responsive">          
<table class="table">
  <thead>
    <tr class="active">
      <th>Quantity</th>
      <th> Product Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>


    <%= render @cart %>


  <tr class="info">
      <td><%= link_to 'Edit', edit_cart_path(@cart) %> </td>
      <td><%= link_to 'Back', carts_path %></td>       
      <td><%= button_to 'Empty Cart' ,  @cart , method: :delete  ,   data:   { confirm: 'Are you sure?' } %> </td> 
  </tr>
    
    
      <tr class="info">
      <td> GRAND TOTAL:</td>
      <td><%=  number_to_currency(@cart.total_price) %> </td>
  </tr>

  </tbody>
</table>

</div> <!-- close table responsive -->