config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do 
  get 'product/latest'

end

    root 'store#index' , as: 'store'

end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  
  #after creating the cart partial , we were unable to acess it . Hence , we are invoking the layout while looking at the store index action. 
  # and that action does not currently set @cart... so we will add the below which will make the partail available .. hopefully. 
 

  include CurrentCart
  before_action :set_cart


  #uncomment once is ready for deployment.    
  #before_action :authenticate_user!
 
  def index
  # here we need to get the product out of the database and dislay in the store
  # ask the model for  list of products that we can sell.
  @products = Product.order(:title)

  end





end 

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<!--<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>   -->


<div class="fluid-container">



<% if notice  %>

<p id="notice"><%= notice %></p>

<% end %>
 
 <!-- removed header-->   
<!-- <h1><center>e-commerce platform</center></h1> --> 
<div class="jumptron"> 

<div class="table-responsive">          
<table class="table">
  <thead>
    <tr class="active">
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

     <% @products.each do |product| %>
          <tr class="info">
       <!-- double check if this is really working . -->
       <td><%= image_tag(product.image_url) %></td>
       <td><%= product.title %></td>
       <td><%= sanitize(product.description) %></td>
       <td><%= number_to_currency(product.price) %></td>
       <td><%= button_to 'Add to Cart' , line_items_path(product_id: product) %></td>
   </tr>

  <% end %>

  </tbody>
</table>

</div> <!-- close table responsive -->

</div>
</div> <!-- close container-->